Создание README
gpb-it-factory/gluharyov-middle-service pull request #2
Opened 2024-05-24 10:55 UTC by CoreXYZ1

Создан предварительный README

2024-05-31 06:07 UTC, vaganov-vadim requested changes
Привет. Есть пара моментов, которые стоит поправить - отметил в комментах.
+ к этому - название PR не по соглашению, перечитай, как указано в практике, и пометь, пожалуйста.

2024-05-31 06:07 UTC, vaganov-vadim commented on .gitignore
> +/.idea/
Кажется, у тебя это не сработало. Файлы из .idea всё равно закоммитились. Надо поправить этот момент.

2024-05-31 06:07 UTC, vaganov-vadim commented on README.md
> +database "Бэкэнд" as db
Технически бэкэнд тоже сервис =)

2024-06-04 13:29 UTC, CoreXYZ1 commented on README.md
> +database "Бэкэнд" as db
Исправил

2024-06-04 13:30 UTC, CoreXYZ1 commented on .gitignore
> +/.idea/
Исправил

2024-06-11 05:18 UTC, vaganov-vadim approved these changes
Аппрув! Погнали дальше =)

2024-06-11 05:19 UTC, merged